language: node_js

node_js:
  # Quote the version number as Travis will interpret 0.10 as 0.1 unless quoted.
  - "0.10"
  - "0.8"
  - "0.6"

before_script:
  - cat /etc/hosts
  - sudo hostname localhost
  - echo 'yes' | sudo add-apt-repository ppa:cubrid/cubrid
  - sudo apt-get update
  - sudo apt-get install cubrid
  - /etc/profile.d/cubrid.sh
  - sudo apt-get install cubrid-demodb
