sudo: required

language: node_js

node_js:
  - 4.4
  - 4.5
  - 4.6
  - 5
  - 6

services:
  - docker

env:
  - CUBRID_VERSION=9.3.6.0002
  - CUBRID_VERSION=9.2.26.0004
  - CUBRID_VERSION=9.2.3.0005
  - CUBRID_VERSION=9.1.0.0218
  - CUBRID_VERSION=9.0.0.0478
  - CUBRID_VERSION=8.4.3.10001
  - CUBRID_VERSION=8.4.1.32003

before_install:
  - docker pull lighthopper/cubrid:$CUBRID_VERSION
  - docker run -d -p 33000:33000 --name cubrid lighthopper/cubrid:$CUBRID_VERSION ./create-start-demodb.sh
  - docker ps -a
  - docker logs cubrid

after_success:
  - npm run coverage

script: npm run test
